image: python:3.10

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE
  DOCKER_TAG: $CI_COMMIT_SHORT_SHA

before_script:
    - mkdir ~/.ssh
    - echo "$HOST_SSH_KEY_BASE64" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa

after_script:
    - rm -f ~/.ssh/id_rsa


stages:
  - lint
  - tests


lint:
    stage: lint
    script:
      - python3 -m pip install wemake-python-styleguide==0.16.1
      - make lint

unit_tests:
    stage: tests
    script:
      - ls
      - make install
      - make run_unit_tests

integration_tests:
    stage: tests
    script:
      - ls
      - make install
      - make run_integration_tests
